//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microbe.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microbe.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///setTile(0, [
        ///    1, 1, 1, 1, 1, 1, 1, 1,
        ///    1, 2, 1, 1, 1, 2, 1, 1,
        ///    1, 1, 1, 1, 1, 2, 1, 1,
        ///    1, 1, 2, 1, 1, 1, 2, 1,
        ///    1, 1, 1, 1, 1, 1, 1, 1,
        ///    1, 1, 1, 1, 1, 1, 1, 1,
        ///    1, 1, 1, 1, 3, 1, 1, 1,
        ///    1, 1, 1, 1, 1, 1, 1, 1
        ///]);
        ///
        ///setTile(1, [
        ///    0, 0, 0, 2, 2, 0, 0, 0,
        ///    0, 0, 0, 2, 2, 0, 0, 0,
        ///    0, 0, 2, 2, 2, 2, 0, 0,
        ///    0, 0, 0, 2, 2, 0, 0, 0,
        ///    0, 2, 2, 2, 2, 2, 2, 0,
        ///    0, 0, 0, 2, 2, 0, 0, 0,
        ///    0, 0, 2, 0, 0, 2, 0, 0,
        ///    0, 0, 2, 0, 0, 2, 0, 0
        ///]);
        ///
        ///var  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note,Frequency
        ///C1,32.70
        ///C#1/Db1,34.65
        ///D1,36.71
        ///D#1/Eb1,38.89
        ///E1,41.20
        ///F1,43.65
        ///F#1/Gb1,46.25
        ///G1,49.00
        ///G#1/Ab1,51.91
        ///A1,55.00
        ///A#1/Bb1,58.27
        ///B1,61.74
        ///C2,65.41
        ///C#2/Db2,69.30
        ///D2,73.42
        ///D#2/Eb2,77.78
        ///E2,82.41
        ///F2,87.31
        ///F#2/Gb2,92.50
        ///G2,98.00
        ///G#2/Ab2,103.83
        ///A2,110.00
        ///A#2/Bb2,116.54
        ///B2,123.47
        ///C3,130.81
        ///C#3/Db3,138.59
        ///D3,146.83
        ///D#3/Eb3,155.56
        ///E3,164.81
        ///F3,174.61
        ///F#3/Gb3,185.00
        ///G3,196.00
        ///G#3/Ab3,207.65
        ///A3,220.00
        ///A#3/Bb3,233.08
        ///B3,246.94
        ///C4,261.63
        ///C#4/Db4,277.18
        ///D4,293.66
        ///D#4/Eb4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string note_frequency {
            get {
                return ResourceManager.GetString("note-frequency", resourceCulture);
            }
        }
    }
}
